[package]
name = "ascii_nom"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "ascii_nom"
path = "src/lib.rs"

[dependencies]
nom="*"
strum="*"
strum_macros = "*"